version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      nuxt:
        patterns:
          - "@nuxtjs/*"
          - "@nuxt/*"
          - "nuxt-*"
          - "nuxt"
      vue:
        patterns:
          - "@vue/*"
          - "vue-*"
          - "vue"
      lint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint-*"
          - "eslint"
          - "husky"
          - "lint-staged"
          - "prettier-*"
          - "prettier"
